// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Express = require("bs-express/src/Express.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Process = require("process");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var setupCorsHack = (app => {
    var cors = require('cors');
    app.use(cors());
  });

function application(port, endpoints) {
  var app = Express.App.make(undefined);
  setupCorsHack(app);
  var router = Express.Router.make(undefined, undefined, undefined, undefined);
  Express.App.useRouter(app, router);
  Belt_List.forEach(endpoints, (function (ep) {
          return Curry._1(ep.useOnRouter, router);
        }));
  var defaultPort = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(Process.env, "PORT"), (function (a) {
              return Number(a) | 0;
            })), 3000);
  var effectivePort = Belt_Option.getWithDefault(port, defaultPort);
  Express.App.listen(app, effectivePort, undefined, (function (param) {
          console.log("Server listening on port", effectivePort);
          
        }), undefined);
  return {
          expressApp: app,
          router: router
        };
}

exports.setupCorsHack = setupCorsHack;
exports.application = application;
/* Express Not a pure module */
