// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Decco = require("decco/src/Decco.js");
var BsCron = require("bs-cron/src/BsCron.bs.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

function makePaymentRequest_encode(v) {
  return Js_dict.fromArray([
              [
                "amount",
                Decco.stringToJson(v.amount)
              ],
              [
                "identifier",
                Decco.stringToJson(v.identifier)
              ]
            ]);
}

var job = BsCron.CronJob.make({
      HASH: /* CronString */870007071,
      VAL: "* * * * *"
    }, (function (param) {
        console.log("Printing every minute");
        
      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

function startProcess(param) {
  job.start();
  
}

exports.makePaymentRequest_encode = makePaymentRequest_encode;
exports.job = job;
exports.startProcess = startProcess;
/* job Not a pure module */
