// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

Belt_Array.map([
      1,
      2
    ], (function (x) {
        return x + 1 | 0;
      }));

/*  Not a pure module */
